### ISSUE TITLE
Dependecies left out during installation

### ISSUE THREAD

**Issue by lkolacek** [containerbuildsystem/osbs-client#490]
I installed osbs-client from Fedora repositories via:
```
dnf install -y osbs-client
```
When running the build the following errors are produced.

Tracebacks:
```
[root@localhost atomic-reactor]# osbs --config /etc/osbs.conf --instance local build -g https://github.com/TomasTomecek/hello-world-container -b master -u lkolacek -c hello-world
Traceback (most recent call last):
  File "/usr/bin/osbs", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2958, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2944, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2971, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycurl' distribution was not found and is required by osbs-client
```
```
[root@localhost atomic-reactor]# osbs --config /etc/osbs.conf --instance local build -g https://github.com/TomasTomecek/hello-world-container -b master -u lkolacek -c hello-world
Traceback (most recent call last):
  File "/usr/bin/osbs", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2958, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2944, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2971, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dockerfile-parse' distribution was not found and is required by osbs-client
```

**Comment by twaugh** [comment]
Seems like the spec file needs updating.

**Comment by twaugh** [comment]
Looking more at this, osbs-client-0.33-2.fc25 requires python3-osbs-client-0.33-2.fc25 (the sub-package providing the Python 3 module), and that in turn requires "python3-pycurl". If I try to remove python3-pycurl, it ends up removing osbs-client.

Similarly for python3-dockerfile-parse.

Which osbs-client version and release did you see this dependency issue with?

**Comment by lkolacek** [comment]
I worked with same package version osbs-client-0.33-2.fc25.noarch. 
You're right that it requires:
python3-dockerfile-parse-0.0.5-7.fc25.noarch
python3-pycurl-7.43.0-4.fc25.x86_64

That's  why I couldn't use osbs command. I tried that again with osbs-3 and run into well known issue:

'''
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/osbs/api.py", line 38, in catch_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/osbs/api.py", line 502, in wait_for_build_to_get_scheduled
    response = self.os.wait_for_build_to_get_scheduled(build_id)
  File "/usr/lib/python3.5/site-packages/osbs/core.py", line 631, in wait_for_build_to_get_scheduled
    build_response = self.wait(build_id, BUILD_FINISHED_STATES + BUILD_RUNNING_STATES)
  File "/usr/lib/python3.5/site-packages/osbs/core.py", line 585, in wait
    for changetype, obj in self.watch_resource("builds", build_id):
  File "/usr/lib/python3.5/site-packages/osbs/core.py", line 560, in watch_resource
    j = json.loads(line)
  File "/usr/lib64/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/osbs-3", line 9, in <module>
    load_entry_point('osbs-client==0.33', 'console_scripts', 'osbs')()
  File "/usr/lib/python3.5/site-packages/osbs/cli/main.py", line 695, in main
    args.func(args, osbs)
  File "/usr/lib/python3.5/site-packages/osbs/cli/main.py", line 289, in cmd_build
    build = osbs.wait_for_build_to_get_scheduled(build_id)
  File "/usr/lib/python3.5/site-packages/osbs/api.py", line 49, in catch_exceptions
    raise OsbsException(cause=ex, traceback=sys.exc_info()[2])
osbs.exceptions.OsbsException: TypeError("the JSON object must be str, not 'bytes'",)
'''

**Comment by twaugh** [comment]
...which is meant to be fixed in that package:

**Comment by ktdreyer** [comment]
This is working on Fedora 30. I think we can close this.

**Comment by twaugh** [comment]
Thanks!
